### ISSUE TITLE
Board Name.

### ISSUE THREAD

**Issue by runahue** [dm5xx/UltraSwitch#2]
Hello Again.

is possible add a Board name?

By default it is Board 0, 1, 2...

Can we add a board name?

thank's a lot.

**Comment by dm5xx** [comment]
Change this in the ultraswitch_content_v1.js to whatever you want to:

for(var b = 0; b < numberOfRelayBoards; b++)
	{

		htmlString += '<div id="container"';

		if(b+1 == numberOfRelayBoards)
			htmlString += ' class="myLast"';

		htmlString += '><div class="rotate">Board '+b+'<img id="greenBullet'+b+'" src="http://h.mmmedia-online.de/dot.png"></div><div id="board'+b+'"></div></div><div id="tempResponse"></div>';
	}

Create static html-code part there and store it. As everything is adjustable with html, js and css, all can be done. If you are not that familiar with web programming, just ask someone ou know, who is doing webpages. he can help you very easily.

Mike

**Comment by runahue** [comment]
Thank's for your answer.

I am trying something like this, but i have some sintax error becouse it doesn't write var content, it writes board0Name ;-)

I will continue investigating.

        for(var b = 0; b < numberOfRelayBoards; b++)
        {

                htmlString += '<div id="container"';
                nombre += 'board'+b+'Name';

                if(b+1 == numberOfRelayBoards)
                        htmlString += ' class="myLast"';
                htmlString += '><div class="rotate">Placa '+b+' '+nombre+'<img id="greenBullet'+b+'" src="http://h.mmmedia-online.de/dot.png"></div><div id="board'+b+'"></div></div><div id="tempResponse"></div>';
        }

        div.innerHTML = htmlString;
}

var textboard0 = ["1","2","3","4","5","6","7","8","9","10","11","12","13","14","15","16"];
var board0Status = [];
var board0Group = [];
var board0Name = 'Reles';

**Comment by dm5xx** [comment]
if you need some help => dm5xx@gmx.de
